[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Vite SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/feed/index.json"
  [headers.values]
  Cache-Control = "public, max-age=60, must-revalidate"

[[headers]]
  for = "/feed/pages/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
